### ISSUE TITLE
Possible to remove noisy log messages?

### ISSUE THREAD

**Issue by FPierre** [recursivefunk/good-env#11]
`ensure` method [internally use `console.log`](https://github.com/recursivefunk/good-env/blob/master/index.js#L110).

In my case, the following:

```js
env.ensure(
  { DB_HOST: { type: 'string' } },
  { DB_PASS: { type: 'string' } },
  { DB_USER: { type: 'string' } },
  { DB_DATABASE: { type: 'string' } },
);
```

Produce:

```bash
triggered string
triggered string
triggered string
triggered string
```

It's too verbose for success case IMO. Would you consider adding verbose log option? Or maybe just remove these `console.log`? :thinking:

**Comment by recursivefunk** [comment]
@FPierre sorry for the delay - didn't catch the notification. You're right. I removed the logging in the latest release `5.1.1` https://github.com/recursivefunk/good-env/pull/13
